"""initial migration

Revision ID: 8310683c514a
Revises: 17fa3e2e3a90
Create Date: 2023-03-15 17:01:46.537886

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8310683c514a'
down_revision = '17fa3e2e3a90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
