"""initial migration

Revision ID: b528105d58a4
Revises: 672b3b2830a1
Create Date: 2023-03-13 16:55:20.178100

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b528105d58a4'
down_revision = '672b3b2830a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('categories_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('created_by')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.drop_constraint('districts_ibfk_1', type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('created_by')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('food_items', schema=None) as batch_op:
        batch_op.drop_constraint('food_items_ibfk_2', type_='foreignkey')
        batch_op.drop_column('created_by')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=255), nullable=True))

    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.drop_constraint('regions_ibfk_1', type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('created_by')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('updated_at', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('address')

    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.VARCHAR(length=255), nullable=True))
        batch_op.create_foreign_key('regions_ibfk_1', 'users', ['created_by'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('food_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('updated_at', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('food_items_ibfk_2', 'users', ['created_by'], ['id'])

    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.VARCHAR(length=255), nullable=True))
        batch_op.create_foreign_key('districts_ibfk_1', 'users', ['created_by'], ['id'])

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.VARCHAR(length=200), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('categories_ibfk_1', 'users', ['created_by'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
