"""initial migration

Revision ID: d60cccd69e45
Revises: 8310683c514a
Create Date: 2023-03-16 11:04:32.505292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd60cccd69e45'
down_revision = '8310683c514a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_constraint('addresses_ibfk_2', type_='foreignkey')
        batch_op.drop_column('region_id')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('categories_ibfk_1', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('categories_ibfk_1', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('addresses_ibfk_2', 'regions', ['region_id'], ['id'])

    # ### end Alembic commands ###
